/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visoes;

import Controladores.ControladorTelaCadastroFilme;
import javax.swing.JFormattedTextField;
import javax.swing.JTextField;

/**
 *
 * @author Lenovo
 */
public class TelaCadastroFilme extends javax.swing.JFrame {
    private final ControladorTelaCadastroFilme controlador;
    /**
     * Creates new form TelaCadastroFilme
     */
    public TelaCadastroFilme() {
        initComponents();
        
        controlador = new ControladorTelaCadastroFilme(this);
      //  controlador.mostraPopUpMeny();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenuEscolheCategoria = new javax.swing.JPopupMenu();
        jMenuItemAcao = new javax.swing.JMenuItem();
        jMenuItemAventura = new javax.swing.JMenuItem();
        jMenuItemComedia = new javax.swing.JMenuItem();
        jMenuItemDocumentario = new javax.swing.JMenuItem();
        jMenuItemFiccaoCientifica = new javax.swing.JMenuItem();
        jMenuItemTerror = new javax.swing.JMenuItem();
        jButtonCategorias = new javax.swing.JButton();
        jButtonAtualizarExcluirCadastroFilme = new javax.swing.JButton();
        jButtonExibeListaFilmes = new javax.swing.JButton();
        jLabelSubtitulo1 = new javax.swing.JLabel();
        jButtonLimpar = new javax.swing.JButton();
        jButtonCadastrar = new javax.swing.JButton();
        jFormattedTextFieldDataLancamento = new javax.swing.JFormattedTextField();
        jTextFieldNomeFilme = new javax.swing.JTextField();
        jTextFieldCategoria = new javax.swing.JTextField();
        jLabelSubtitulo2 = new javax.swing.JLabel();
        jLabelSubtitulo = new javax.swing.JLabel();
        jLabelTitulo1 = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();

        jMenuItemAcao.setLabel("Ação");
        jMenuItemAcao.setName(""); // NOI18N
        jMenuItemAcao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItemAcaoMousePressed(evt);
            }
        });
        jPopupMenuEscolheCategoria.add(jMenuItemAcao);

        jMenuItemAventura.setLabel("Aventura");
        jMenuItemAventura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItemAventuraMousePressed(evt);
            }
        });
        jPopupMenuEscolheCategoria.add(jMenuItemAventura);

        jMenuItemComedia.setLabel("Comédia");
        jMenuItemComedia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItemComediaMousePressed(evt);
            }
        });
        jPopupMenuEscolheCategoria.add(jMenuItemComedia);
        jMenuItemComedia.getAccessibleContext().setAccessibleName("comédia");

        jMenuItemDocumentario.setLabel("Documentário");
        jMenuItemDocumentario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItemDocumentarioMousePressed(evt);
            }
        });
        jPopupMenuEscolheCategoria.add(jMenuItemDocumentario);

        jMenuItemFiccaoCientifica.setLabel("Ficção científica");
        jMenuItemFiccaoCientifica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItemFiccaoCientificaMousePressed(evt);
            }
        });
        jPopupMenuEscolheCategoria.add(jMenuItemFiccaoCientifica);

        jMenuItemTerror.setLabel("Terror");
        jMenuItemTerror.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItemTerrorMousePressed(evt);
            }
        });
        jPopupMenuEscolheCategoria.add(jMenuItemTerror);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCategorias.setText("Categorias");
        jButtonCategorias.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButtonCategoriasMouseMoved(evt);
            }
        });
        jButtonCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCategoriasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jButtonAtualizarExcluirCadastroFilme.setText("Atualizar ou excluir cadastro de filme");
        jButtonAtualizarExcluirCadastroFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarExcluirCadastroFilmeActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAtualizarExcluirCadastroFilme, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, -1, -1));

        jButtonExibeListaFilmes.setText("Exibe lista de filmes cadastrados");
        jButtonExibeListaFilmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExibeListaFilmesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExibeListaFilmes, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, -1, -1));

        jLabelSubtitulo1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabelSubtitulo1.setText("Data de lançamento:");
        getContentPane().add(jLabelSubtitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 180, -1));

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 80, -1));

        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, -1, -1));

        try {
            jFormattedTextFieldDataLancamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedTextFieldDataLancamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 130, 30));

        jTextFieldNomeFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeFilmeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNomeFilme, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 130, 30));
        getContentPane().add(jTextFieldCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 130, 30));

        jLabelSubtitulo2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabelSubtitulo2.setText("Categoria:");
        getContentPane().add(jLabelSubtitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 100, -1));

        jLabelSubtitulo.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabelSubtitulo.setText("Nome do filme:");
        getContentPane().add(jLabelSubtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 170, -1));

        jLabelTitulo1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTitulo1.setText("Cadastro de  filme");
        getContentPane().add(jLabelTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 270, -1));

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelTitulo.setText("Cenaflix");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 190, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeFilmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeFilmeActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
       controlador.inserirFilmeNoBanco();
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
       controlador.limparCampos();
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonExibeListaFilmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExibeListaFilmesActionPerformed
        controlador.mostrarListaFilmesNaTela();
    }//GEN-LAST:event_jButtonExibeListaFilmesActionPerformed

    private void jButtonAtualizarExcluirCadastroFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarExcluirCadastroFilmeActionPerformed
        TelaAtualizacaoExclusao telaAtualizacaoExclusao = new TelaAtualizacaoExclusao();
        telaAtualizacaoExclusao.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonAtualizarExcluirCadastroFilmeActionPerformed

    private void jMenuItemAcaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemAcaoMousePressed
        controlador.mostraFilmesAcao();
    }//GEN-LAST:event_jMenuItemAcaoMousePressed

    private void jMenuItemComediaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemComediaMousePressed
        controlador.mostraFilmesComedia();
    }//GEN-LAST:event_jMenuItemComediaMousePressed

    private void jMenuItemAventuraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemAventuraMousePressed
        controlador.mostraFilmesAventura();
    }//GEN-LAST:event_jMenuItemAventuraMousePressed

    private void jMenuItemTerrorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemTerrorMousePressed
     controlador.mostraFilmesTerror();
    }//GEN-LAST:event_jMenuItemTerrorMousePressed

    private void jMenuItemDocumentarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemDocumentarioMousePressed
        controlador.mostraFilmesDocumentario();
    }//GEN-LAST:event_jMenuItemDocumentarioMousePressed

    private void jMenuItemFiccaoCientificaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemFiccaoCientificaMousePressed
        controlador.mostraFilmesFiccaoCientifica();
    }//GEN-LAST:event_jMenuItemFiccaoCientificaMousePressed

    private void jButtonCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCategoriasActionPerformed
      
          jPopupMenuEscolheCategoria.show(this, 50, 50);
        
    }//GEN-LAST:event_jButtonCategoriasActionPerformed

    private void jButtonCategoriasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCategoriasMouseMoved
        jPopupMenuEscolheCategoria.show(this, 50, 50);
    }//GEN-LAST:event_jButtonCategoriasMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroFilme().setVisible(true);
            }
        });
    }

    public JFormattedTextField getjFormattedTextFieldDataLancamento() {
        return jFormattedTextFieldDataLancamento;
    }

    public void setjFormattedTextFieldDataLancamento(JFormattedTextField jFormattedTextFieldDataLancamento) {
        this.jFormattedTextFieldDataLancamento = jFormattedTextFieldDataLancamento;
    }

    public JTextField getjTextFieldCategoria() {
        return jTextFieldCategoria;
    }

    public void setjTextFieldCategoria(JTextField jTextFieldCategoria) {
        this.jTextFieldCategoria = jTextFieldCategoria;
    }

    public JTextField getjTextFieldNomeFilme() {
        return jTextFieldNomeFilme;
    }

    public void setjTextFieldNomeFilme(JTextField jTextFieldNomeFilme) {
        this.jTextFieldNomeFilme = jTextFieldNomeFilme;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizarExcluirCadastroFilme;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonCategorias;
    private javax.swing.JButton jButtonExibeListaFilmes;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataLancamento;
    private javax.swing.JLabel jLabelSubtitulo;
    private javax.swing.JLabel jLabelSubtitulo1;
    private javax.swing.JLabel jLabelSubtitulo2;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTitulo1;
    private javax.swing.JMenuItem jMenuItemAcao;
    private javax.swing.JMenuItem jMenuItemAventura;
    private javax.swing.JMenuItem jMenuItemComedia;
    private javax.swing.JMenuItem jMenuItemDocumentario;
    private javax.swing.JMenuItem jMenuItemFiccaoCientifica;
    private javax.swing.JMenuItem jMenuItemTerror;
    private javax.swing.JPopupMenu jPopupMenuEscolheCategoria;
    private javax.swing.JTextField jTextFieldCategoria;
    private javax.swing.JTextField jTextFieldNomeFilme;
    // End of variables declaration//GEN-END:variables
}
