/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visoes;

import Controladores.ControladorTelaCadastroFilme;
import javax.swing.JFormattedTextField;
import javax.swing.JTextField;

/**
 *
 * @author Lenovo
 */
public class TelaCadastroFilme extends javax.swing.JFrame {
    private final ControladorTelaCadastroFilme controlador;
    /**
     * Creates new form TelaCadastroFilme
     */
    public TelaCadastroFilme() {
        initComponents();
        
        controlador = new ControladorTelaCadastroFilme(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelSubtitulo1 = new javax.swing.JLabel();
        jButtonLimpar = new javax.swing.JButton();
        jButtonCadastrar = new javax.swing.JButton();
        jFormattedTextFieldDataLancamento = new javax.swing.JFormattedTextField();
        jTextFieldNomeFilme = new javax.swing.JTextField();
        jTextFieldCategoria = new javax.swing.JTextField();
        jLabelSubtitulo2 = new javax.swing.JLabel();
        jLabelSubtitulo = new javax.swing.JLabel();
        jLabelTitulo1 = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelSubtitulo1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabelSubtitulo1.setText("Data de lançamento:");
        getContentPane().add(jLabelSubtitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 180, -1));

        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 80, -1));

        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, -1, -1));

        try {
            jFormattedTextFieldDataLancamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedTextFieldDataLancamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 130, 30));

        jTextFieldNomeFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeFilmeActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNomeFilme, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 130, 30));
        getContentPane().add(jTextFieldCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 130, 30));

        jLabelSubtitulo2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabelSubtitulo2.setText("Categoria:");
        getContentPane().add(jLabelSubtitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 100, -1));

        jLabelSubtitulo.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabelSubtitulo.setText("Nome do filme:");
        getContentPane().add(jLabelSubtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 130, -1));

        jLabelTitulo1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTitulo1.setText("Cadastro de  filme");
        getContentPane().add(jLabelTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 270, -1));

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelTitulo.setText("Cenaflix");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 190, 40));

        jLabelFundo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        getContentPane().add(jLabelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeFilmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeFilmeActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
       controlador.inserirFilmeNoBanco();
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
       controlador.limparCampos();
    }//GEN-LAST:event_jButtonLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFilme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroFilme().setVisible(true);
            }
        });
    }

    public JFormattedTextField getjFormattedTextFieldDataLancamento() {
        return jFormattedTextFieldDataLancamento;
    }

    public void setjFormattedTextFieldDataLancamento(JFormattedTextField jFormattedTextFieldDataLancamento) {
        this.jFormattedTextFieldDataLancamento = jFormattedTextFieldDataLancamento;
    }

    public JTextField getjTextFieldCategoria() {
        return jTextFieldCategoria;
    }

    public void setjTextFieldCategoria(JTextField jTextFieldCategoria) {
        this.jTextFieldCategoria = jTextFieldCategoria;
    }

    public JTextField getjTextFieldNomeFilme() {
        return jTextFieldNomeFilme;
    }

    public void setjTextFieldNomeFilme(JTextField jTextFieldNomeFilme) {
        this.jTextFieldNomeFilme = jTextFieldNomeFilme;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataLancamento;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelSubtitulo;
    private javax.swing.JLabel jLabelSubtitulo1;
    private javax.swing.JLabel jLabelSubtitulo2;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTitulo1;
    private javax.swing.JTextField jTextFieldCategoria;
    private javax.swing.JTextField jTextFieldNomeFilme;
    // End of variables declaration//GEN-END:variables
}
